# Install packages
library (Seurat)
library (ggplot2)
library (patchwork)
library (dplyr)
library(hdf5r)

# Load datasets
d3aus <- Read10X_h5("~/d3aus_filtered_feature_bc_matrix.h5")
d4vus <- Read10X_h5("~/d4vus_filtered_feature_bc_matrix.h5")

# Create Seurat objects
data.d3aus <- CreateSeuratObject(d3aus, project = "d3aus", min.cells = 3, min.features = 200)
data.d4vus <- CreateSeuratObject(d4vus, project = "d4vus", min.cells = 3, min.features = 200)

# Count mito
data.d3aus[["percent.mt"]] <- PercentageFeatureSet(data.d3aus, pattern = "^MT-")
data.d4vus[["percent.mt"]] <- PercentageFeatureSet(data.d4vus, pattern = "^MT-")

# Filter and downsample
data.d4vus <- subset(data.d4vus, subset = nFeature_RNA > 3750 & nFeature_RNA < 8000 & percent.mt <11 & percent.mt>5)
data.d3aus <- subset(data.d3aus, subset = nFeature_RNA  > 5000 & nFeature_RNA <9000 & percent.mt <11 & percent.mt >5)
subset(x = data.d4vus, downsample = 940)
subset(x = data.d3aus, downsample = 940)

# Merge, normalize, scale data
alldata <- merge(data.d3aus, c(data.d4vus), add.cell.ids=c("day3artery","day4vein"))
alldata <- NormalizeData(alldata)
all.genes <- rownames(alldata)
alldata <- ScaleData(alldata, features = all.genes)

# View features
VlnPlot(alldata, features = "ACTB", pt.size = 0.1) + NoLegend()
alldata <- subset(alldata, subset = ACTB>2)
alldata <- subset(alldata, subset = YWHAZ>0.8) 
VlnPlot(alldata, features = "nCount_RNA", pt.size = 0.1) + NoLegend()
VlnPlot(alldata, features = "percent.mt", pt.size = 0.1) + NoLegend()
VlnPlot(alldata, features = "nFeature_RNA", pt.size = 0.1) + NoLegend()

# Find most variable features
alldata <- FindVariableFeatures(alldata, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(alldata), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(alldata)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2

# Dimension reduction
alldata <- RunPCA(alldata, npcs = 100, ndims.print = 1:5, nfeatures.print = 5)

# Examine and visualize PCA results a few different ways
print(alldata[["pca"]], dims = 1:5, nfeatures = 5)
DimPlot(alldata, reduction = "pca")

# Elbow plot
ElbowPlot(alldata)

# Find neighbors, clusters
alldata <- FindNeighbors(alldata, dims = 1:10)
alldata <- FindClusters(alldata, resolution = 0.1)
alldata <- RunUMAP(alldata, dims = 1:10)
DimPlot(alldata, reduction = "umap", cols = c( "#660066","#FF0000","#8064A2","green","#e4a3f0","#64a27f"))
alldata <- RenameIdents(object = alldata, `0` = "Vein endothelial 1", `1` = "Artery endothelial 1", `2` = "Vein endothelial 2",`3` = "Mesenchymal V",`4` = "Vein endothelial3", `5` = "Mesenchymal A")
saveRDS(alldata, file = "~/arteryvein2022.rds")

# Import packages for ShinyCell
reqPkg = c("data.table", "Matrix", "hdf5r", "reticulate", "ggplot2", 
           "gridExtra", "glue", "readr", "RColorBrewer", "R.utils", "Seurat")
newPkg = reqPkg[!(reqPkg %in% installed.packages()[,"Package"])]
if(length(newPkg)){install.packages(newPkg)}

reqPkg = c("shiny", "shinyhelper", "data.table", "Matrix", "DT", "hdf5r", 
           "reticulate", "ggplot2", "gridExtra", "magrittr", "ggdendro")
newPkg = reqPkg[!(reqPkg %in% installed.packages()[,"Package"])]
if(length(newPkg)){install.packages(newPkg)}

library(Seurat)
library(ShinyCell)
library(patchwork)
library(rsconnect)
library(remotes)
library(base64enc)
library("Matrix")

# Import files
seu = readRDS("/users/stanfordkevin/Downloads/arteryvein2022.rds")
scConf = createConfig(seu)
showLegend(scConf)
showOrder(scConf)

# Modify colours and labels
scConf = modColours(scConf, meta.to.mod = "seurat_clusters", 
                    new.colours= c("#660066","#FF0000","#8064A2","green","#e4a3f0","#64a27f"))

scConf = modColours(scConf, meta.to.mod = "orig.ident", 
                    new.colours= c("#FF0000","#660066"))

scConf = modLabels(scConf, meta.to.mod = "seurat_clusters", 
                   new.labels = c("Vein endothelial 1", "Artery endothelial 1", "Vein endothelial 2","Mesenchymal V","Vein endothelial3", "Mesenchymal A"))

showLegend(scConf)

# Cite paper
checkConfig(scConf, seu)
citation = list(
  authors  = "Lay Teng Ang, Alana T. Nguyen, Kevin J. Liu, Angela Chen, Xiaochen Xiong, Matthew Curtis, Renata M. Martin, Brian C. Raftry, Chun Yi Ng, Uwe Vogel, Angelika Lander, Benjamin J. Lesch, Jonas L. Fowler, Alyssa R. Holman, Timothy Chai, Siva Vijayakumar, Fabian P. Suchy, Toshinobu Nishimura, Joydeep Bhadury, Matthew H. Porteus, Hiromitsu Nakauchi, Christine Cheung, Steven C. George, Kristy Red-Horse, Joseph B. Prescott & Kyle M. Loh",  title   = "Generating human artery and vein cells from pluripotent stem cells
highlights the arterial tropism of Nipah and Hendra viruses",
  journal = "Cell",
  year    = "2022")

# Make shiny app
makeShinyApp(seu, scConf, gene.mapping = TRUE, gex.assay = "RNA", gex.slot = c("data","scale.data","counts"), shiny.title = "Generating human artery and vein cells from pluripotent stem cells
highlights the arterial tropism of Nipah and Hendra viruses",shiny.dir = "~/arteryveinscRNA/", shiny.footnotes = citation,default.gene1 = "CDH5", default.gene2 = "SOX17",default.multigene = c("CXCR4","EFNB2","DLL4", "UNC5B", "APLN","NR2F2","FLRT2","NT5E","APLNR")) 
rsconnect::setAccountInfo(name='anglab', token='A32B2D1D8EC80A3DCA18FE87D57BF4C1', secret='Y8MOzKBtRcH+XvwM2IJMcL2e4gEQunRTw0VC7bUo')
rsconnect::deployApp("/users/stanfordkevin/Downloads/arteryveinscRNA/")

sessionInfo()
